jobs:
  compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ matrix.os }}-maven-

          '
    - continue-on-error: true
      name: Build with maven
      run: mvn -B --errors --activate-profiles ci --no-transfer-progress package -DskipTests
    strategy:
      matrix:
        java:
        - '8'
        os:
        - ubuntu-latest
        - windows-latest
  test:
    needs: compile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ matrix.os }}-maven-

          '
    - continue-on-error: true
      name: Build and test with maven
      run: mvn -B --errors --activate-profiles ci --no-transfer-progress package
    - continue-on-error: true
      if: failure()
      name: Archive test results and logs
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.java }}-${{ matrix.os }}
        path: sshd-*/target/surefire-*
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        os:
        - ubuntu-latest
        - windows-latest
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
